Protect Routes
joinum/parzival pull request #281
Opened 2023-05-16 19:26 UTC by MarioRodrigues10

2023-05-19 14:52 UTC, ruioliveira02 requested changes
Whenever I try to create a:
- Company
- Job
- Recruiter (though for a different reason: name used to be company and hasn't been properly updated)
- FAQS

the page is crashing, as it is being directed to a `show`, despite having no ID. Print:
![image](https://github.com/joinum/parzival/assets/70754369/ee71e5d7-97fd-4f36-ba4e-02d8d65bc56d)

2023-05-27 11:02 UTC, ruioliveira02 reviewed
![image](https://github.com/joinum/parzival/assets/70754369/8087934a-2de4-459d-9f34-048102c80dee)
Fix this error pls :pleading_face: 

![image](https://github.com/joinum/parzival/assets/70754369/1170085f-b79b-431c-ba8c-4101a0bfbeb9)
 Also this

2023-05-30 13:13 UTC, ruioliveira02 requested changes
I am worried about two things:

1. I am not seeing any distinctions between the non admin roles (staff, attendee and recruiter). 
2. Staff has way too much access. The only creative action (meaning performing an action that changes the state of the database) is redeeming tasks and products.

2023-06-03 11:36 UTC, RuiL1904 commented on lib/parzival_web/live/app/announcement_live/index.html.heex
> +      <%= if @current_user.role in [:admin, :staff] do %>
Only an admin should make an annoucement

2023-06-03 11:36 UTC, RuiL1904 commented on lib/parzival_web/live/app/announcement_live/show.html.heex
> +      <%= if @current_user.role in [:admin, :staff] do %>
Only an admin should edit an annoucement

2023-06-03 11:36 UTC, RuiL1904 commented on lib/parzival_web/live/app/gamification/mission_live/index.html.heex
> +      <%= if @current_user.role in [:admin, :staff] do %>
Only an admin should create a mission

2023-06-03 11:36 UTC, RuiL1904 commented on lib/parzival_web/live/app/gamification/mission_live/show.html.heex
> +      <%= if @current_user.role in [:admin, :staff] do %>
Only an admin should edit a mission

2023-06-04 13:28 UTC, ruioliveira02 requested changes
## Bugs

![image](https://github.com/joinum/parzival/assets/70754369/b94dcdd5-029d-40f8-a26c-684bdd9066ec)
Route: `http://localhost:4000/app/offers/<uuid>/edit`

![image](https://github.com/joinum/parzival/assets/70754369/2c0d6bfb-e7e3-4226-8bc5-4da8f72a749f)
When accessing this route as an attendee (needless to say an attendee shouldn't even have access to this). Same for `companies_new/new`

![image](https://github.com/joinum/parzival/assets/70754369/abce0859-fc89-40e6-8da4-c810964f115b)
http://localhost:4000/app/companies/15748dc5-9a74-4e3f-bdc9-50640512b669/edit as attendee. Same for profile edit

## Authorization problems

![image](https://github.com/joinum/parzival/assets/70754369/06a4780a-3907-4c81-9624-2c015c3ac75e)
Staff cannot edit difficulties

![image](https://github.com/joinum/parzival/assets/70754369/1a6f8522-e495-4198-9b8f-5505a1dcb336)
This one is debatable, but I think staff should not have access to this

Why isn't there any link for the scanner route for staff? That is the single most important page for them

Attendees are not able click tasks as to get the QR code to redeem them.

Recruiters cannot edit offers

Staff and recruiters are being redirected to `/app` if they enter the url `/admin/scanner` manually

2023-06-04 15:29 UTC, MarioRodrigues10 commented
> Attendees are not able click tasks as to get the QR code to redeem them.

![image](https://github.com/joinum/parzival/assets/93675410/4cf25cb0-47b8-4835-9216-75e0d32aedbc)

2023-06-04 15:38 UTC, MarioRodrigues10 commented
> When accessing this route as an attendee (needless to say an attendee shouldn't even have access to this). Same for companies_new/new
> http://localhost:4000/app/companies/15748dc5-9a74-4e3f-bdc9-50640512b669/edit as attendee. Same for profile edit


In production they will receive a 500 page

2023-06-04 16:41 UTC, ruioliveira02 commented
> > When accessing this route as an attendee (needless to say an attendee shouldn't even have access to this). Same for companies_new/new
> 
> > http://localhost:4000/app/companies/15748dc5-9a74-4e3f-bdc9-50640512b669/edit as attendee. Same for profile edit
> 
> In production they will receive a 500 page

Doesn't matter. You should never return a 500. 500 means something you were not expecting happen, and is an error situation. This is not an error situation, this is a lack of authorization problem. They should not even have access to that route

2023-06-04 16:55 UTC, ruioliveira02 approved these changes

2023-06-04 16:56 UTC, merged